<?php
/**
 * @file
 *   My tabs Angular App module
 */

/**
 * Implements hook_menu().
 */
function tabs_menu() {
  $items['tabs'] = array(
    'title' => 'Tabs ui',
    'page callback' => 'tabs_ui_page',
    //'access callback' => TRUE,
    'access arguments' => array('access content'),
   	// 'menu_name' => 'main-menu',  
    // 'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}


/**
 * Implements hook_theme().
 */
function tabs_theme() {
  return array(
    'tabs_ui' => array(
      'template' => 'tabs-ui',
    ),
  );
}




/**
 * Tabs page callback.
 */
function tabs_ui_page(){
  // Set the path
  $path = drupal_get_path('module', 'tabs');

  // Load angular
  drupal_add_library('angularjs', 'angularjs');

  // Load the app
  drupal_add_js($path . '/js/tabsUi.gen.js');
  drupal_add_js($path . '/bower_components/angular-aria/angular-aria.js');
  drupal_add_js($path . '/bower_components/angular-animate/angular-animate.js');
  drupal_add_js($path . '/bower_components/angular-material/angular-material.js');

  drupal_add_css($path . '/css/bootstrap.css');

  // Return the HTML template
  return theme('tabs_ui');
}